### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by evenator** [swri-robotics/bag-reader-java#12]
This is a minor aesthetic gripe, but I'm going to gripe about it anyway.

The Changelog shows this is version 1.3 (and the commit history has commits that suggest releases), but the releases aren't tagged, so they don't show up in the "releases" tab on github.

**Comment by pjreed** [comment]
Oops, I think I had just not bothered to tag releases here because I assumed anybody who cared about it would be pulling the artifacts from the Maven repository... but yeah, it'd be good to have tags on the Git repo, so I'll add that.

**Comment by pjreed** [comment]
All done.
