### ISSUE TITLE
Exposing `myFieldNameMap` publicly

### ISSUE THREAD

**Issue by azymnis** [swri-robotics/bag-reader-java#21]
For a given `MessageType` I'd like to know all available fields. Seems like this info is stored in `MessageType.myFieldNameMap`. Why not expose this publicly?

**Comment by pjreed** [comment]
I'd rather not expose the member variable because other classes shouldn't modify its contents, but being able to get the list of fields is perfectly reasonable.  Would adding a method like this work for you?

```java
    public List<String> getFieldNames() {
        return Lists.newArrayList(myFieldNameMap.keySet());
    }
```

**Comment by azymnis** [comment]
@pjreed sorry yes that's what I meant. That sounds great
