### ISSUE TITLE
Issue with ArrayType of UInt8

### ISSUE THREAD

**Issue by nichet** [swri-robotics/bag-reader-java#24]
Hi,
For a data in the bag with the value of [180, 248, 151, 192] as an array of UInt8, if field.getAsShorts() is used, we get [-19208, -26688]. IMO, another method should be added to get the correct value with the short type:
~~~~
 public short[] getUInt8sWithShorts() {
        byte[] tmp = new byte[myData.capacity()];
        byte[] shorts = new short[myData.capacity()];
        myData.get(tmp);
        // convert each byte (b) to short with ((short) b) & 0xff
        return shorts;
    }
~~~~

**Comment by pjreed** [comment]
Ok, I've been able to reproduce both of the issues you've reported.  The one for reading uint8s is easy to fix, although do you think it would be preferable to add a new method just for that or to modify the existing `getAsShorts` method to handle unsigned integers properly?

**Comment by nichet** [comment]
I think 2 use cases should be handled when the ROS bag contains:
1) Array of Shorts
2) Array of UInt8s
For 1) getAsShorts() is fine. But for 2) another method is required may be getAsShortsForUInt8s().
Similarly, getAsIntsForUShorts(), getAsLongsForUInts(), etc.

**Comment by nichet** [comment]
I looked the code you committed it handles both cases, so no need to add a new method.

**Comment by pjreed** [comment]
I'm sure that all of the other array methods have the same problem when reading unsigned values, so I'll make similar changes for them, too.

**Comment by pjreed** [comment]
I think I've fixed all of the similar issues with other types, and I added some more documentation; if you'd like to try building from my source branch, let me know if everything is working for you now.
