### ISSUE TITLE
Issue with ArrayType of Float64Type

### ISSUE THREAD

**Issue by nichet** [swri-robotics/bag-reader-java#25]
For an array of Float64Type, if the value in the bag is [1.003062456558312] and field.getAsDoubles() is used, the returned value is -4.2284959582596674E20.
BTW great lib.

**Comment by pjreed** [comment]
It looks like this was just an endianness issue; should be fixed with the latest commit to my PR.

**Comment by nichet** [comment]
Indeed probably endianness issue.
It was fine with a primitive Float64Type, but not with array of Float64Type.

**Comment by nichet** [comment]
The changes work fine. When do you plan to push it to Maven repository?
Thanks for the quick support.

**Comment by pjreed** [comment]
I just pushed version 1.9.0 to Maven Central, so hopefully you'll see it soon.  Thanks for reporting the issue!
