### ISSUE TITLE
Logging required, maybe document? 

### ISSUE THREAD

**Issue by tobidelbruck** [swri-robotics/bag-reader-java#27]
Thanks for this nice contribution. Maybe the README.md could suggest the simplest way to add the required dependency on the Logger that is used, since it is not part of core Java logger? I found this
https://www.slf4j.org/download.html
but it seems to include a mole of Apache stuff, not just a jar file.  Suggestions very welcome, thanks.

**Comment by tobidelbruck** [comment]
Same for Guava, 
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap

I think I'm getting these missing dependencies because our project doesn't use Maven; we have a jar folder with all dependencies; these jars are put on the classpath.
Unfortunately, Guava is only available via Maven, and does not supply a jar we can use.
Suggestions welcome. Transitioning to maven would be nice but a major effort for us (our project started in 2007).

I found https://github.com/google/guava/wiki/Release19, which does supply jar, javadoc, and src for Guava; will give this a try.

**Comment by pjreed** [comment]
Depending on what build system you're using, you might be able to add in a dependency manager without having to convert everything to Maven; for example, [Ivy](http://ant.apache.org/ivy/history/latest-milestone/index.html) plugs nicely into Ant.

But anyway, for your other issues:

1. The bag reader uses the SLF4J API, which is a common logging API that has many different implementations.  I like Logback as an implementation, but if you want to use the core Java logger, you can just include the binding for it; I think this page describes how, but I'm not 100% sure because SLF4J's page isn't responding for me at the moment: http://slf4j.org/manual.html#swapping

2. For any other dependencies that you want to just find the jar files for, it's pretty easy to use Maven to obtain all of a project's dependencies like so:

```bash
$ git clone git@github.com:swri-robotics/bag-reader-java.git
$ cd bag-reader-java/
$ mvn dependency:copy-dependencies
$ ls target/dependency/
byte-buddy-1.5.5.jar        commons-codec-1.10.jar     guava-18.0.jar         hamcrest-library-1.3.jar       jackson-core-2.6.5.jar      junit-4.12.jar             logback-core-1.1.5.jar  mockito-core-2.2.21.jar  slf4j-api-1.7.16.jar
byte-buddy-agent-1.5.5.jar  commons-compress-1.10.jar  hamcrest-core-1.3.jar  jackson-annotations-2.6.0.jar  jackson-databind-2.6.5.jar  logback-classic-1.1.5.jar  lz4-1.5.0.jar           objenesis-2.4.jar
```

Next time I'm updating things, I'll go ahead and add some more detailed instructions to the README on how to obtain dependencies.

**Comment by tobidelbruck** [comment]
A really big thanks for this very useful answer!!  You are the greatest!
I was struggling to find a way to use some kind of package manager with our ant-based project and ivy is the way to go.  

BTW, to use ivy in a netbeans java ant project, this is a good guide for beginners:
http://wiki.netbeans.org/FaqIvy . The only thing missing from it was to get ivy accessible to all the project users, I had to download and add ivy-2.4.0.jar to our project static library folder. 

In case it is of interest (and this is quite outside bag-reader-java, so apologies), here are contents of my ivy.xml and build.xml files. Sorry for the long post, but it took me quite a long time as a newbie to figure out all the places that needed to be modified. This is with JDK 1.8, netbeans 8.2.

**ivy.xml**

_For ivy.xml, I found a lot of jars that we used in our project by using maven search, but I had to be careful to choose the correct version and also the exact correct artifact id to get all the required jar files dependencies. I have not yet figure out how to handle libraries with native JNI dependencies that vary between windows and linux platforms._


<ivy-module version="2.0">
    <info organisation="org.jaerproject" module="jaer" />

    <dependencies>
         <dependency org="com.github.swri-robotics" name="bag-reader-java" rev="1.9.0" />
     </dependencies>
</ivy-module>

**build.xml**

<project name="jAER" default="default" basedir="." **xmlns:ivy="antlib:org.apache.ivy.ant"**>

  <path id="ivy.lib.path">
        <fileset dir="jars" includes="ivy-2.4.0.jar"/>
    </path>
    <taskdef resource="org/apache/ivy/ant/antlib.xml"
             uri="antlib:org.apache.ivy.ant" classpathref="ivy.lib.path"/>

  <target name="-ivy-retrieve">
        <ivy:retrieve/> 
        <pathconvert property="ivy.classpath.computed" dirsep="/" pathsep=":">
            <path>
                <fileset dir="lib" includes="*.jar"/>
            </path>
            <map from="${basedir}${file.separator}" to=""/>
        </pathconvert>
        <propertyfile file="nbproject/project.properties">
            <entry operation="=" key="ivy.classpath" value="${ivy.classpath.computed}"/>
        </propertyfile>
    </target>

    <target name="-pre-compile" depends="-ivy-retrieve"/>
    <target name="-pre-compile-single" depends="-ivy-retrieve"/>

   <target name="-post-clean">
        <delete dir="lib"/>
    </target>

**Comment by pjreed** [comment]
Cool, good to hear that's working for you.  I'll go ahead and close this issue.
