### ISSUE TITLE
trying to read ArrayType with complex objects

### ISSUE THREAD

**Issue by tobidelbruck** [swri-robotics/bag-reader-java#28]
Great package.  I'm having some trouble (probably also as a newbie to rosbags in general) in reading an ArrayType that contains more complex objects. The field "events" in the message is an ArrayType.  The code I'm running now for understanding it is derived from the examples:
```java
file.forMessagesOnTopic("/dvs/events", new MessageHandler() {
            @Override
            public boolean process(MessageType message, Connection connection) {
                try {
                    Field f=message.getField("events");
                    List<String> fns=message.getFieldNames();
                    ArrayType eventArray= message.<ArrayType>getField("events");
                    String type=eventArray.getType(); // "Event[]"
                    List<Field> eventFields=eventArray.getFields();
                    int nEvents=eventFields.size();
                    
                    for(Field ff:eventFields){
                        String typeString=ff.getType();
                    }
                    return true;
                } catch (UninitializedFieldException ex) {
                    Logger.getLogger(ExampleRosBagReader.class.getName()).log(Level.SEVERE, null, ex);
                    return false;
                }
            }
        });
```

The structure is shown in this image from netbean variables view:
![image](https://user-images.githubusercontent.com/10061874/35448596-fad4b074-02ba-11e8-9d04-5dcf8bb065e0.png)

Each basic thing I want to read out is one "Event" that has short x,y, Timestamp, and boolean polarity. In the example in the image, there are nEvents=132 of these events. The iterator over eventFields just returns typeString "event".  
It could well be that I'm missing some basic knowledge about ROS file data structure.

Any ideas how to read out this complex custom type from the ArrayType would be appreciated.

**Comment by pjreed** [comment]
Reading in arrays of complex data types is admittedly kind of ugly.  You have to:

1. Use `MessageType.getField(String name)` to get the `ArrayType` object
2. Use `ArrayType.getFields()` to get an array of those values
3. Individually cast those to `MessageType` objects
4. Call `MessageType.getField(String name)` on them to access their fields.

I added a unit test in PR #29 that demonstrates how to get some complex values out of a [sensor_msgs/PointCloud2](http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html) message.

I would definitely like to add a friendlier interface for working with arrays, but I haven't had any great ideas on what it should look like and haven't personally needed it, so it hasn't been a high priority.

**Comment by tobidelbruck** [comment]
Thank you, this should be really helpful. You are also teaching quite a bit about how to properly do tests and manage git projects via pull requests, even on your own code. I see that your test reads the PointCloud2 message to validate that the fields match the expected fields.
The messages I'm decoding are in https://github.com/uzh-rpg/rpg_dvs_ros/tree/master/dvs_msgs/msg .
I will give it a try and post the results here.

**Comment by tobidelbruck** [comment]
Thanks again, this example was helpful, particularly the hint (which is not at all obvious) to cast the resulting ArrayType field back to a MessageType to access its elements (in this case, x,y,ts,polarity).

Here is my code. Some of it won't make sense, since it refers to classes in https://github.com/SensorsINI/jaer and uses the ROS messages from https://github.com/uzh-rpg/rpg_dvs_ros/tree/master/dvs_msgs/msg

```
 final EventPacket<PolarityEvent> eventPacket = new EventPacket(PolarityEvent.class);
		file.forMessagesOnTopic("/dvs/events", new MessageHandler() {
			@Override
			public boolean process(MessageType message, Connection connection) {
				try {
					Field f = message.getField("events");
					List<String> fns = message.getFieldNames();
					ArrayType data = message.<ArrayType>getField("events");
					String type = data.getType(); // "Event[]"
					List<Field> eventFields = data.getFields();
					int nEvents = eventFields.size();
					OutputEventIterator<PolarityEvent> outItr = eventPacket.outputIterator();
					for (Field eventField : eventFields) {
						MessageType eventMsg = (MessageType) eventField;
						// https://github.com/uzh-rpg/rpg_dvs_ros/tree/master/dvs_msgs/msg]
						PolarityEvent e = outItr.nextOutput();
						int x = eventMsg.<UInt16Type>getField("x").getValue();
						int y = eventMsg.<UInt16Type>getField("y").getValue();
						boolean pol = eventMsg.<BoolType>getField("polarity").getValue();
						int tsMs = (int) eventMsg.<TimeType>getField("ts").getValue().getTime();
						int tsNs = (int) eventMsg.<TimeType>getField("ts").getValue().getNanos();
						e.x = (short) x;
						e.y = (short) y;
						e.polarity = pol ? Polarity.On : Polarity.Off;
						e.timestamp = tsMs * 1000 + tsNs / 1000;
					}
					System.out.println(eventPacket.toString());
					return true;
				} catch (UninitializedFieldException ex) {
					Logger.getLogger(ExampleRosBagReader.class.getName()).log(Level.SEVERE, null, ex);
					return false;
				}
			}
		});

```
This whole process of reading the files might be too slow, but I have to see. There is a lot of access of HashMaps and casting and getting going on here to access what amounts to arrays of primitive values. Anyhow I will give it a try. Thanks again!

**Comment by tobidelbruck** [comment]
This is only a related issue, but am making note of it here.  To read in the rosbag for rendering it in jAER, we probably need a kind of stateful reader that can iterate over messages in time order, including several topics, as in this python example: http://wiki.ros.org/rosbag/Code%20API .  In that example, a for loop iterates over messages related to two topics.  For our purposes, we need to maintain a state for the reader and call it repeatedly to get more data either in forward or reverse direction. Also we need some way to move the reader to a specified point in the bag.  This whole thing looks to be pretty complicated so I will move to working with bag-reader project. Will open issue on building bag-reader-java that is separate.

**Comment by pjreed** [comment]
Good to hear that worked for you.  For what it's worth, I don't know if it will be fast enough for you, but I did some very rough benchmarking back when I first made this library, and I can tell you that it should be at least 20x faster than the official Python bag reader. ;-)

Note that in the Python example you linked to, it is not actually guaranteed to loop over messages in time order.  It will iterate over them in the order they were recorded in the bag file, which is *usually* in time order, but it's not guaranteed.  If you're doing something that requires the messages to be in order, the easiest solution is probably to write a Python script to post-process your bags and rewrite them so that everything is in order.

Also, just for reference, it is easy to move forward when reading a bag file but harder to move backward.   Every chunk header stores the size of data in the chunk, so it's possible to skip over it to the next header, but there's know way of knowing how far you need to go back unless you're also saving all of those chunk sizes as you skip over them; also, while the bag format provides a way to store indexes in a bag file, in practice the `rosbag record` command does not generate indexes, so most bags do not have them at all.

To be able to go back and forth and go to an arbitrary message, you'd need to first scan through every message in the back file and build your own index of the locations of every message, which is possible but will slow down reading the file by a bit.

**Comment by tobidelbruck** [comment]
Thanks for the additional tips. I wrote a method now to make a MsgIterator that I can call repeatedly to get messages related to a list of topics. It works, to my amazement. However there seems to be some big memory leak since my memory usage grew to about 3GB after playing back one file.   It seems to be either longs or some kind of HashMap objects according to the netbeans profiler. I notice that when playing back the file (about a 2GB recording), there are pauses while the MsgIterator seems to search for the next topic that matches. The memory usage (as reported by TaskManager) seems to grow a lot during these periods. But it just grows continuously in any case. 
I could be doing something completely incorrectly here. 


Here is my code


```java
private static String[] TOPICS = {"/dvs/events", "/dvs/image_raw", "/dvs/imu"};

public RosbagFileInputStream(File f, AEChip chip) throws BagReaderException {
        setFile(f);
        this.chip = chip;
        log.info("opening rosbag file " + f + " for chip " + chip);
        bagFile = BagReader.readFile(file);
//        bagFile.printInfo(); // debug
        conns = bagFile.getConnections();
        ArrayList<Connection> myConnections = new ArrayList();
        for (Connection conn : conns) {

            String topic = conn.getTopic();
//            log.info("connection "+conn+" has topic "+topic);
            for (String t : TOPICS) {
                if (t.equals(topic)) {
                    log.info("topic matches " + t + "; adding this connection to myConnections. This message has definition " + conn.getMessageDefinition());
                    myConnections.add(conn);
                }
            }

        }
        chunkInfos = bagFile.getChunkInfos();
        try{
            channel = bagFile.getChannel();
            msgIterator = new MsgIterator(chunkInfos, myConnections, channel);
        } catch (IOException e) {
            throw new BagReaderException(e);
        }
    }

 private MessageType getNextMsg() throws BagReaderException {
        if (msgIterator.hasNext()) {
            return msgIterator.next();
        } else {
            throw new BagReaderException("EOF");
        }
    }

private AEPacketRaw getNextRawPacket() {
        try {
            MessageType message = getNextMsg();
            Field f = message.getField("events");
//            List<String> fns = message.getFieldNames();
            ArrayType data = message.<ArrayType>getField("events");
//            String type = data.getType(); // "Event[]"
            List<Field> eventFields = data.getFields();
            int nEvents = eventFields.size();
            OutputEventIterator<ApsDvsEvent> outItr = eventPacket.outputIterator();
            int sizeY=chip.getSizeY();
            for (Field eventField : eventFields) {
                MessageType eventMsg = (MessageType) eventField;
                // https://github.com/uzh-rpg/rpg_dvs_ros/tree/master/dvs_msgs/msg]
                PolarityEvent e = outItr.nextOutput(); // reuse the packet: clear it and get first event
                int x = eventMsg.<UInt16Type>getField("x").getValue();
                int y = eventMsg.<UInt16Type>getField("y").getValue();
                boolean pol = eventMsg.<BoolType>getField("polarity").getValue();
                int tsMs = (int) eventMsg.<TimeType>getField("ts").getValue().getTime();
                int tsNs = (int) eventMsg.<TimeType>getField("ts").getValue().getNanos();
                e.x = (short) x;
                e.y = (short) (sizeY-y-1);
                e.polarity = pol ? PolarityEvent.Polarity.On : PolarityEvent.Polarity.Off;
                e.type=(byte)(pol?1:0);
                e.timestamp = tsMs * 1000 + tsNs / 1000;
            }
            aePacketRaw=chip.getEventExtractor().reconstructRawPacket(eventPacket); // reconstructs jAER raw event packet from the cooked EventPacket
//            System.out.println(eventPacket.toString());
        } catch (UninitializedFieldException ex) {
            Logger.getLogger(ExampleRosBagReader.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }catch(BagReaderException bre){
            log.info(bre.toString());
            return null;
        }
        return aePacketRaw;
    }


```

**Comment by pjreed** [comment]
At a glance, that code seems reasonable; it's also entirely possible that the bag reader is leaking memory somewhere when iterating through things, although I haven't seen that personally.  Can you tell from NetBeans' profiler where those objects are being allocated?

Also, in your example code, I don't see where "aePacketRaw" is declared; does that come from somewhere else?

**Comment by tobidelbruck** [comment]
I can't see where they are being allocated, but I think it is related to the findNext() method in BagFile.  I see hundreds of MB of Long and Object[]; somehow strangely related to the RosBagInputStream PropertyChangeSupport.
BTW, I branched jaer now and pushed the RosBagInputStream to 
https://github.com/SensorsINI/jaer/blob/ivy-bagreader/src/net/sf/jaer/eventio/ros/RosbagFileInputStream.java
Definitely still a work in progress. 
In this commit, I replaced the original topic iterator with an iterator that uses your generated index for a particular topic. I will need to enhance your getMessageOnTopicAtIndex to generate an index that includes several topics combined in some way, and sorted in timestamp order.

```

synchronized private MessageType getNextMsg() throws BagReaderException {
        MessageType msg = null;
        if (!wasIndexed) {
            log.warning("generating indexes for ros file, please wait...");
        }
        try {
            msg = bagFile.getMessageOnTopicAtIndex(TOPICS[0], msgPosition);
        } catch (ArrayIndexOutOfBoundsException e) {
            if (isRepeat()) {
                try {
                    rewind();
                    return getNextMsg();
                } catch (IOException ex) {

                }
            }
        }
        if (!wasIndexed) {
            log.warning("done indexing");
        }
        wasIndexed = true;
        msgPosition++;
        return msg;
//        if (msgIterator == null) {
//            msgIterator = getMsgIterator();
//        }
//        if (msgIterator.hasNext()) {
//            msgPosition++;
//            return msgIterator.next();
//        } else {
//            throw new BagReaderException("EOF");
//        }
    }

```

The aePacketRaw is the basic container in jAER for raw event data (int timestamps and int addresses)
https://github.com/SensorsINI/jaer/blob/ivy-bagreader/src/net/sf/jaer/aemonitor/AEPacketRaw.java

I still have a lot to do, to make the reader compatible with previous AEFileInputStream, which allows grabbing a particular time window or number of events, can skip to any event position, and can play backwards and forwards. That will require buffering the results of BagReader reads.
