### ISSUE TITLE
Build Failure (probably incorrect pom file)

### ISSUE THREAD

**Issue by StevenC1987** [swri-robotics/bag-reader-java#35]
I'm completely new to both ros and maven (and relatively inexperienced with java). 
I tried following the readme, but it says to add a dependency to my Maven pom.xml. The only pom file I can find is the one in the root folder of the project, but it makes no sense to me to add it there, so what am I supposed to do with it?
If I add it anyway, maven immediately complains about it when trying to build it. And when I don't add the dependency anywhere the build fails with a MojoExecutionException.

I'm sorry if this is not the way to ask about this, I'm new to github as well.

**Comment by pjreed** [comment]
That readme is assuming you're using Maven as the build system for your Java project; if you are using Maven, the `pom.xml` file in your root folder is the right place to add it; if that's giving you build errors, could you paste the error you're seeing here?

If you're not using Maven, let me know what your project is using and we'll see if we can figure out the right thing to add.

**Comment by StevenC1987** [comment]
I'm sorry, I realized later that I misunderstood and I was using it wrong.
Thanks for the reply.
