### ISSUE TITLE
To get the field types

### ISSUE THREAD

**Issue by iniyanp** [swri-robotics/bag-reader-java#36]
Hi,

Is there a way to get `myFields` of `connection.getMessageCollection.getMessageType`.  I see only `getFieldNames` (List[String]). I am trying to extract the type of fields.

After looking into the code, I see `myFields` field. But there is no getter for that field. 
Is there any other way that I can get myFields so that I can extract type of fields dynamically.

Thanks

**Comment by pjreed** [comment]
Currently there's not a way to get a list of the types of fields in a message, although I've got nothing against adding it if that would be useful.

It's probably sub-optimal if you're trying to list all of the types of fields, but you can get a list of the field names, and then print the type of each individual field; that would look something like:
```java
List<String> fieldNames = mt.getFieldNames();
for( String fieldName : fieldNames ) {
    Field field = mt.getField(fieldName);
    System.out.println("Type : " + field.getType());
}

**Comment by iniyanp** [comment]
Thanks for that. It works.
