### ISSUE TITLE
How to read array of uint8

### ISSUE THREAD

**Issue by journey-wang** [swri-robotics/bag-reader-java#39]
```
uint32 step         
uint8[] data   

msg.<UInt32Type>getField("step").getValue() . can read "step".
```
How to get "data" field? 
Thanks

**Comment by pjreed** [comment]
To get an array, first You need to get it as an ArrayType and then call the appropriate .get method to convert it to the type of data in the array.  There are some examples in the unit tests; for example, https://github.com/swri-robotics/bag-reader-java/blob/6120626bd200ede967cb884377d378c62d103c5e/src/test/java/com/github/swrirobotics/bags/reader/TestBagFile.java#L71 .

In that case, with a std_msgs/Int8MultiArray message:
```
std_msgs/MultiArrayLayout layout
int8[] data
```

The code to obtain the values in the array looks like this:
```java
ArrayType data = message.getField("data");
byte[] values = data.getAsBytes();
```

**Comment by journey-wang** [comment]
Thanks very much

**Comment by pjreed** [comment]
No problem!
