### ISSUE TITLE
How can I parse any random bag file.

### ISSUE THREAD

**Issue by prajyotkoli123** [swri-robotics/bag-reader-java#44]
For parsing bag file I use any random bag file and I don't no which type of data present on topic.
So in that case how can I parse bag file and extract required topic msg data?

**Comment by pjreed** [comment]
Messages in a bag file are stored by connection, and the header for each connection has metadata about the topic and messages on it.  Refer to the documentation for the bag format at http://wiki.ros.org/Bags/Format/2.0 .

For example, if you just wanted to iterate over every connection in a bag and print out information about it, you could do something like this:

```java
        File file = new File("src/test/resources/PointCloud2.bag");
        BagFile bag = new BagFile(file.getPath());
        final int[] count = {0};
        bag.read();
        for (Connection conn : bag.getConnections()) {
            System.out.println("Connection " + conn.getConnectionId());
            System.out.println("  Topic: " + conn.getTopic());
            System.out.println("  Type: " + conn.getType());
            System.out.println("  Definition: " + conn.getMessageDefinition());
        }
```

If you have a specific topic you want to read, you can use the `forMessagesOnTopic` method on the `BagFile` class to iterate over them; see the unit tests in `TestBagFile.java` for examples.  You do need to know the data types of fields in order to deserialize them, but with the information available in the Connection object for that message, you could determine the data type of each field and handle it however you need.

**Comment by prajyotkoli123** [comment]
Thank you so much for help.

**Comment by prajyotkoli123** [comment]
while(itr<topicInfos.size())
       {
        bag.forMessagesOnTopic(topicInfos.get(itr++).getName(), new
MessageHandler() {
            @Override
            public boolean process(MessageType mt, Connection cnctn) {

                ArrayList<String> FieldNames=new ArrayList<String>();
                FieldNames=(ArrayList<String>)mt.getFieldNames();
               String data=null;

              for(int i =0 ; i<FieldNames.size();i++)
              {
                     double
dat[]=mt.<ArrayType>getField(FieldNames.get(i)).getAsDoubles();

System.out.println(mt.<ArrayType>getField(FieldNames.get(i)).getAsDoubles());

              }
             return true;
            }
        });
    }

I iterate like this as shown in above code. I want parse all topic message
data in one loop but in this case i get exception at
double dat[]=mt.<ArrayType>getField(FieldNames.get(i)).getAsDoubles() the
data in next iteration may float/int/char.
So in that case how i do it.

**Comment by pjreed** [comment]
The getter methods on the Field (such as `getAsDoubles`) do not cast the data type for you; they assume the data you're getting is a matching type and will throw an exception if it's not.  If you don't know what type of data you're parsing, you will need to check before you get it.  You could do something like this:

```java
        bag.forMessagesOnTopic("/topic", new MessageHandler() {
            @Override
            public boolean process(MessageType mt, Connection cnctn) {
                List<String> fieldNames = mt.getFieldNames();

                Logger logger = LoggerFactory.getLogger(this.getClass());
                logger.info("Found " + fieldNames.size() + " fields.");

                for(String fieldName : fieldNames)
                {
                    logger.info("Processing field: " + fieldName);
                    Field field = mt.getField(fieldName);
                    String type = field.getType();
                    if ("float64[]".equals(type)) {
                        double[] values = ((ArrayType)field).getAsDoubles();
                        logger.info("Printing field " + fieldName + " as doubles:");
                        for (double value : values) {
                            logger.info(Double.toString(value));
                        }
                    }
                    else {
                        logger.info("Field " + fieldName + " had type " + type);
                    }
                }
                return true;
            }
        });
```

**Comment by prajyotkoli123** [comment]
Thanks for help.

**Comment by pjreed** [comment]
Sure, no problem.
