### ISSUE TITLE
Error MessageType cannot be cast to ArrayType

### ISSUE THREAD

**Issue by jawhster** [swri-robotics/bag-reader-java#55]
Related to https://github.com/swri-robotics/bag-reader-java/issues/28, but getting an error when try to get the ArrayType of fields from pose field of nav_msgs/Odometry. Format like below

nav_msgs/Odometry
  > String child_frame_id
  > Header
    > Long seq
    > Time stamp
    > String frame_id
  > Pose
    > Pose
      > Position
      > Orientation
    > Double covariance

```
bag.forMessagesOfType("nav_msgs/Odometry", new MessageHandler() {
      @Override
      public boolean process(MessageType message, Connection connection) {
        try {
          
          //get pose

          Field f = message.getField("pose");
          List<String> fns = message.getFieldNames();
          ArrayType data = message.<MessageType>getField("pose").<ArrayType>getField("pose");
          String type = data.getType(); // "Event[]"
          List<Field> eventFields = data.getFields();
          for (Field eventField : eventFields) {
            MessageType eventMsg = (MessageType) eventField;
            System.out.println(eventMsg.getName());
          }
}
```

Error reads 

> com.github.swrirobotics.bags.reader.messages.serialization.MessageType cannot be cast to com.github.swrirobotics.bags.reader.messages.serialization.ArrayType
java.lang.ClassCastException: com.github.swrirobotics.bags.reader.messages.serialization.MessageType cannot be cast to com.github.swrirobotics.bags.reader.messages.serialization.ArrayType
	at org.mitre.cdp.autonomy.Foo$1.process(Foo.java:80)
	at com.github.swrirobotics.bags.reader.BagFile.forMessagesOfType(BagFile.java:366)
	at org.mitre.cdp.autonomy.Foo.messageFieldNames(Foo.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at ...

**Comment by pjreed** [comment]
That's because the `pose` you're trying to get is not an array, but an instance of a `geometry_msgs/Pose` message.  Something like this instead will read and print the x values for every `nav_msgs/Odometry` message in a bag:
```java
        bag.forMessagesOfType("nav_msgs/Odometry", (message, connection) -> {
            MessageType pose = message.getField("pose");
            MessageType geoPose = pose.getField("pose");
            MessageType position = geoPose.getField("position");
            Float64Type x = position.getField("x");
            try {
                System.out.println("X: " + x.getValue());
            } catch (UninitializedFieldException e) {
                e.printStackTrace();
            }
            return true;
        });
```

**Comment by jawhster** [comment]
Perfect, thanks so much. I’ll give a try and close out. Thanks again for prompt reply and the repo itself
